### ISSUE TITLE
Fail to generate lines between markers

### ISSUE THREAD

**Issue by CryptoTimp** [themustafaomar/jsvectormap#25]
document.addEventListener("DOMContentLoaded", function() {
			var map = new JsVectorMap({
				map: "world",
				selector: "#world_map",	
				zoomButtons: true,
				markers: [
					{ name: 'Foo', coords: [-14.2350, -51.9253], style: { fill: 'red' }},
					{ name: 'Bar', coords: [35.8617, 104.1954], style: { fill: 'red' }}
				],
				lines: [{
					from: 'Foo', to: 'Bar',
					style: {
					stroke: 'red',
					strokeWidth: 1.5
					}
				}],
			});
			window.addEventListener("resize", () => {
				map.updateSize();
			});
		});
		
		Generates a map with markers, but no lines...

**Comment by navsahote97** [comment]
same issue for me...

**Comment by CryptoTimp** [comment]
Are you using the below in your <head>?

<link rel="stylesheet" href="https://unpkg.com/jsvectormap/dist/css/jsvectormap.css" />
<script src="https://unpkg.com/jsvectormap"></script>
<script src="https://unpkg.com/jsvectormap/dist/maps/world.js"></script>

**Comment by themustafaomar** [comment]
It would be nice if you provided an example that reproduces the issue.

And take a look at this example: https://themustafaomar.com/open-source/jsvectormap/examples/lines

This is an example using the code you've just provided and it's working: https://codepen.io/themustafaomar/pen/RwoYzgO

BTW `JsVectorMap()` constructor is no longer working, please use `jsVectorMap()`

**Comment by CryptoTimp** [comment]
Hi,

I just tried changing my constructor to "js" instead of "Js". Didnt have any luck with this. 

Does it matter that i am requiring via the CDN?
![image](https://user-images.githubusercontent.com/55949777/110253605-23067080-7f83-11eb-9186-acc1d61a3463.png)

I am trying to run this in electron. With the following code:
![image](https://user-images.githubusercontent.com/55949777/110253628-39143100-7f83-11eb-9942-e600cca9d803.png)

Pointing to this div in my html:
![image](https://user-images.githubusercontent.com/55949777/110253639-47624d00-7f83-11eb-8e48-26474a16c3cd.png)

Do you have any recommendations? I have tried replicating my code towards yours from the docs but have no luck.

Thanks

**Comment by themustafaomar** [comment]
Nope, it doesn't matter, I'm using the exact same links already at Codepen, and it's working.

That's a little bit weird to me, more than one example is working for me
I think this issue may be related to Electron which unfortunately I've never worked with!

Try to troubleshoot this issue by:

Executing this code exactly in a normal JavaScript environment if it's working we know for sure this is something related to Electron.

Please let me know if it's failing only in Electron, and I'll try to figure out a way to fix this.

**Comment by CryptoTimp** [comment]
I have downloaded your repo with examples. Below is in the index.html (code from your codepen)
![image](https://user-images.githubusercontent.com/55949777/110297135-0b62d280-7feb-11eb-9bce-4e367d118c29.png)

On running this i am presented with this:
![image](https://user-images.githubusercontent.com/55949777/110297286-3816ea00-7feb-11eb-942b-f85f6e949878.png)

When running with the same code from previous post i am presented with the same:
![image](https://user-images.githubusercontent.com/55949777/110297543-86c48400-7feb-11eb-9df6-96fc4d4072e0.png)

**Comment by CryptoTimp** [comment]
In electron producing this error when trying to import css CDN could be linked?
![image](https://user-images.githubusercontent.com/55949777/110304910-09e9d800-7ff4-11eb-9e4c-a722470497a6.png)

**Comment by themustafaomar** [comment]
The samples don't work currently, I'm gonna fix them very soon.

Please try again and create a new file and use CDN links with your exact same config and let me know!

**Comment by CryptoTimp** [comment]
Sure will give this a go, please do let me know when the examples are working as this will greatly help me troubleshoot the problem!

Thanks

**Comment by themustafaomar** [comment]
Done!

**Comment by CryptoTimp** [comment]
Still an issue here with my map:

See how the markers are fine but it doesnt want to draw a line between two of them:
![image](https://user-images.githubusercontent.com/55949777/110604033-8ceb6980-817f-11eb-87de-4e096108f188.png)

Source (using CDN):
![image](https://user-images.githubusercontent.com/55949777/110603969-7c3af380-817f-11eb-9ea8-28a7190e129a.png)

**Comment by themustafaomar** [comment]
You didn't tell me where that's failing ???

Does it work in normal JavaScript (Browser)?

And please stop using images to share your code, I want to copy and paste that code to test it!
